import 'dart:math';
import 'package:blood_donation_app/screens/common/pick_location_osm.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../../models/blood_request_model.dart';
import '../../../providers/request_provider.dart';
import '../../../repositories/blood_request_repository.dart';
import '../../../services/donor_matching_service.dart';

class RecipientRequestScreen extends StatefulWidget {
  const RecipientRequestScreen({super.key});

  @override
  State<RecipientRequestScreen> createState() => _RecipientRequestScreenState();
}

class _RecipientRequestScreenState extends State<RecipientRequestScreen> {
  final _form = GlobalKey<FormState>();
  final _repo = BloodRequestRepository.instance;
  final DonorMatchingService _donorMatchingService = DonorMatchingService();

  final _hospitalCtr = TextEditingController();
  final _notesCtr = TextEditingController();
  final _phoneCtr = TextEditingController();
  final _recipientNameCtr = TextEditingController();

  String _bloodType = 'A+';
  String _urgency = 'normal';
  int _units = 1;
  DateTime? _neededBy;
  int _searchRadius = 10;

  double? _pickedLat;
  double? _pickedLng;
  String _pickedAddress = '';

  bool _submitting = false;

  final _bloodTypes = const ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
  final _urgencies = const ['low', 'normal', 'high', 'emergency'];

  @override
  void dispose() {
    _hospitalCtr.dispose();
    _notesCtr.dispose();
    _phoneCtr.dispose();
    _recipientNameCtr.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final now = DateTime.now();
    final picked = await showDatePicker(
      context: context,
      initialDate: _neededBy ?? now,
      firstDate: now,
      lastDate: now.add(const Duration(days: 60)),
    );
    if (picked != null) setState(() => _neededBy = picked);
  }

  Future<void> _openMap() async {
    final result = await Navigator.of(context).push<Map<String, dynamic>>(
      MaterialPageRoute(builder: (_) => const PickLocationScreen()),
    );

    if (result != null) {
      setState(() {
        _pickedLat = (result['lat'] as num).toDouble();
        _pickedLng = (result['lng'] as num).toDouble();
        _pickedAddress = (result['address'] as String?)?.trim() ?? '';
      });
    }
  }

  Future<void> _submit() async {
    if (!_form.currentState!.validate()) return;
    if (_pickedLat == null || _pickedLng == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please pick a location on the map (Abbottabad).')),
      );
      return;
    }

    setState(() => _submitting = true);

    try {
      final user = FirebaseAuth.instance.currentUser!;
      final userDoc =
      await FirebaseFirestore.instance.collection('users').doc(user.uid).get();
      final requesterName =
          (userDoc.data()?['fullName'] ?? userDoc.data()?['name'] ?? '') as String? ??
              '';

      // Create BloodRequest model first
      final request = BloodRequest(
        id: '', // Will be generated by repository
        requesterId: user.uid,
        requesterName: requesterName,
        bloodType: _bloodType,
        units: _units,
        urgency: _urgency,
        city: 'Abbottabad',
        address: _pickedAddress,
        hospital: _hospitalCtr.text.trim(),
        notes: _notesCtr.text.trim(),
        phone: _phoneCtr.text.trim(),
        location: GeoPoint(_pickedLat!, _pickedLng!),
        status: 'pending',
        neededBy: _neededBy,
        searchRadius: _searchRadius,
        latitude: _pickedLat!,
        longitude: _pickedLng!,
        potentialDonors: [],
        createdAt: DateTime.now(),
        expiresAt: DateTime.now().add(Duration(hours: 1)),
      );

      print('🚀 Starting blood request creation process...');
      print('🕒 Request will expire at: ${DateTime.now().add(Duration(hours: 1))}');

      // FIXED: Use the repository directly instead of provider since provider returns void
      final requestId = await _repo.createRequest(
        requesterId: request.requesterId,
        requesterName: request.requesterName,
        city: request.city,
        bloodType: request.bloodType,
        urgency: request.urgency,
        units: request.units,
        location: request.location!,
        address: request.address,
        hospital: request.hospital,
        notes: request.notes,
        phone: request.phone,
        neededBy: request.neededBy,
        searchRadius: request.searchRadius,
        expirationMinutes: 60,
      );

      print('✅ Blood request created with ID: $requestId');

      // FIXED: Create updated request with the generated ID
      final createdRequest = BloodRequest(
        id: requestId,
        requesterId: request.requesterId,
        requesterName: request.requesterName,
        bloodType: request.bloodType,
        units: request.units,
        urgency: request.urgency,
        city: request.city,
        address: request.address,
        hospital: request.hospital,
        notes: request.notes,
        phone: request.phone,
        location: request.location,
        status: 'pending', // Keep as pending until donors are matched
        neededBy: request.neededBy,
        searchRadius: request.searchRadius,
        latitude: request.latitude,
        longitude: request.longitude,
        potentialDonors: request.potentialDonors,
        createdAt: request.createdAt,
        expiresAt: request.expiresAt,
      );

      if (!mounted) return;

      // FIXED: Use the enhanced donor matching with compatibility (without notifications)
      print('🔍 Finding compatible donors for blood type: $_bloodType');
      final compatibleDonors = await _donorMatchingService.findCompatibleDonors(createdRequest);

      print('🎯 Found ${compatibleDonors.length} compatible donors within $_searchRadius km');

      if (compatibleDonors.isNotEmpty) {
        print('📢 Processing ${compatibleDonors.length} compatible donors...');

        // Update request with potential donors
        await FirebaseFirestore.instance.collection('blood_requests').doc(createdRequest.id).update({
          'potentialDonors': compatibleDonors.map((donor) => donor.userId).toList(),
          'matchingDonorsCount': compatibleDonors.length,
          'status': 'pending', // Keep as pending for donor acceptance
          'updatedAt': FieldValue.serverTimestamp(),
        });

        print('✅ Successfully added ${compatibleDonors.length} potential donors to request');
      } else {
        print('❌ No compatible donors found within $_searchRadius km radius');

        // Update request status even if no donors found
        await FirebaseFirestore.instance.collection('blood_requests').doc(createdRequest.id).update({
          'status': 'pending',
          'matchingDonorsCount': 0,
          'updatedAt': FieldValue.serverTimestamp(),
        });

        // Show warning if no donors found
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('⚠️ No donors found within $_searchRadius km. Try increasing search radius.'),
              backgroundColor: Colors.orange,
              duration: Duration(seconds: 5),
            ),
          );
        }
      }

      // FIXED: Refresh provider data
      final provider = Provider.of<RequestProvider>(context, listen: false);
      await provider.fetchMyRequests();

      // Show success message with detailed information
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  '🎉 Request Created Successfully!',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 4),
                Text(
                  compatibleDonors.isNotEmpty
                      ? '✅ Found ${compatibleDonors.length} donors • 1-hour timer started'
                      : '⚠️ No donors in area • 1-hour timer started',
                  style: const TextStyle(fontSize: 12),
                ),
              ],
            ),
            duration: const Duration(seconds: 6),
            backgroundColor: compatibleDonors.isNotEmpty ? Colors.green : Colors.orange,
            behavior: SnackBarBehavior.floating,
          ),
        );

        // Navigate back after successful creation
        Future.delayed(Duration(seconds: 2), () {
          if (mounted) {
            Navigator.pop(context);
          }
        });
      }

    } catch (e) {
      print('❌ Error creating blood request: $e');
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                '❌ Failed to create request',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 4),
              Text(
                e.toString(),
                style: const TextStyle(fontSize: 12),
              ),
            ],
          ),
          backgroundColor: Colors.red,
          behavior: SnackBarBehavior.floating,
          duration: const Duration(seconds: 5),
        ),
      );
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  // Calculate distance between two coordinates using Haversine formula
  double _calculateDistance(double lat1, double lon1, double lat2, double lon2) {
    const double earthRadius = 6371; // kilometers

    double dLat = _toRadians(lat2 - lat1);
    double dLon = _toRadians(lon2 - lon1);

    double a = sin(dLat / 2) * sin(dLat / 2) +
        cos(_toRadians(lat1)) * cos(_toRadians(lat2)) *
            sin(dLon / 2) * sin(dLon / 2);

    double c = 2 * atan2(sqrt(a), sqrt(1 - a));
    double distance = earthRadius * c;

    return distance;
  }

  double _toRadians(double degrees) {
    return degrees * pi / 180;
  }

  // Get urgency icon based on level
  IconData _getUrgencyIcon(String urgency) {
    switch (urgency) {
      case 'emergency':
        return Icons.emergency;
      case 'high':
        return Icons.warning_amber;
      case 'normal':
        return Icons.info;
      case 'low':
        return Icons.low_priority;
      default:
        return Icons.bloodtype;
    }
  }

  // Get urgency color based on level
  Color _getUrgencyColor(String urgency) {
    switch (urgency) {
      case 'emergency':
        return Colors.red;
      case 'high':
        return Colors.orange;
      case 'normal':
        return Colors.blue;
      case 'low':
        return Colors.green;
      default:
        return Colors.grey;
    }
  }

  // Get blood type color
  Color _getBloodTypeColor(String bloodType) {
    switch (bloodType) {
      case 'A+': return Colors.red.shade600;
      case 'A-': return Colors.red.shade800;
      case 'B+': return Colors.blue.shade600;
      case 'B-': return Colors.blue.shade800;
      case 'AB+': return Colors.purple.shade600;
      case 'AB-': return Colors.purple.shade800;
      case 'O+': return Colors.green.shade600;
      case 'O-': return Colors.green.shade800;
      default: return Colors.grey.shade600;
    }
  }

  @override
  Widget build(BuildContext context) {
    final addr = (_pickedLat == null || _pickedLng == null)
        ? 'No location selected'
        : '$_pickedAddress\n(${_pickedLat!.toStringAsFixed(5)}, ${_pickedLng!.toStringAsFixed(5)})';

    return Scaffold(
      backgroundColor: const Color(0xFFF6F9FB),
      appBar: AppBar(
        elevation: 0,
        title: const Text('Request Blood'),
        centerTitle: true,
        flexibleSpace: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              colors: [Color(0xFF67D5B5), Color(0xFF4AB9C5)],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(18),
        child: Form(
          key: _form,
          child: Column(
            children: [
              // Request Preview Card
              if (_bloodType.isNotEmpty && _pickedLat != null)
                _buildRequestPreview(),

              // Patient/Recipient Section
              _section(
                'Patient / Recipient Details',
                Column(
                  children: [
                    _tf('Recipient Name (optional)', _recipientNameCtr),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                          child: DropdownButtonFormField<String>(
                            value: _bloodType,
                            isExpanded: true,
                            items: _bloodTypes
                                .map((b) => DropdownMenuItem(
                              value: b,
                              child: Row(
                                children: [
                                  Container(
                                    padding: const EdgeInsets.all(4),
                                    decoration: BoxDecoration(
                                      color: _getBloodTypeColor(b),
                                      shape: BoxShape.circle,
                                    ),
                                    child: Icon(Icons.bloodtype,
                                        color: Colors.white, size: 16),
                                  ),
                                  const SizedBox(width: 8),
                                  Text(
                                    b,
                                    style: const TextStyle(fontWeight: FontWeight.w600),
                                  ),
                                ],
                              ),
                            ))
                                .toList(),
                            onChanged: (v) => setState(() => _bloodType = v!),
                            decoration: const InputDecoration(
                              labelText: 'Blood Type',
                              border: OutlineInputBorder(),
                              isDense: true,
                              prefixIcon: Icon(Icons.bloodtype),
                            ),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: DropdownButtonFormField<String>(
                            value: _urgency,
                            isExpanded: true,
                            items: _urgencies
                                .map((u) => DropdownMenuItem(
                              value: u,
                              child: Row(
                                children: [
                                  Icon(_getUrgencyIcon(u),
                                      color: _getUrgencyColor(u),
                                      size: 18),
                                  const SizedBox(width: 8),
                                  Text(
                                    u.toUpperCase(),
                                    style: TextStyle(
                                      fontWeight: FontWeight.w600,
                                      color: _getUrgencyColor(u),
                                    ),
                                  ),
                                ],
                              ),
                            ))
                                .toList(),
                            onChanged: (v) => setState(() => _urgency = v!),
                            decoration: const InputDecoration(
                              labelText: 'Urgency Level',
                              border: OutlineInputBorder(),
                              isDense: true,
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                          child: TextFormField(
                            initialValue: '1',
                            key: ValueKey(_units),
                            decoration: const InputDecoration(
                              labelText: 'Units Required',
                              border: OutlineInputBorder(),
                              isDense: true,
                              prefixIcon: Icon(Icons.bloodtype_outlined),
                            ),
                            keyboardType: TextInputType.number,
                            onChanged: (v) {
                              final n = int.tryParse(v) ?? 1;
                              setState(() => _units = n.clamp(1, 6));
                            },
                            validator: (v) {
                              final n = int.tryParse(v ?? '');
                              if (n == null || n < 1 || n > 6) return 'Enter 1-6 units';
                              return null;
                            },
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: InkWell(
                            onTap: _pickDate,
                            child: InputDecorator(
                              decoration: const InputDecoration(
                                labelText: 'Needed By (optional)',
                                border: OutlineInputBorder(),
                                isDense: true,
                                prefixIcon: Icon(Icons.calendar_today),
                              ),
                              child: Text(
                                _neededBy == null
                                    ? 'Select date'
                                    : '${_neededBy!.day}/${_neededBy!.month}/${_neededBy!.year}',
                                style: TextStyle(
                                  color: _neededBy == null
                                      ? Colors.grey
                                      : Colors.black87,
                                  fontWeight: _neededBy == null ? FontWeight.normal : FontWeight.w600,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 16),

              // Location & Search Radius Section
              _section(
                'Location & Donor Search',
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _infoRow('City', 'Abbottabad'),
                    const SizedBox(height: 8),
                    Card(
                      color: Colors.blueGrey[50],
                      child: Padding(
                        padding: const EdgeInsets.all(12),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Icon(Icons.location_on,
                                    color: _pickedLat == null ? Colors.grey : Colors.green,
                                    size: 16),
                                const SizedBox(width: 4),
                                Text(
                                  'Selected Location:',
                                  style: TextStyle(
                                    fontWeight: FontWeight.w600,
                                    color: _pickedLat == null ? Colors.grey : Colors.blueGrey[700],
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 4),
                            Text(
                              addr,
                              style: TextStyle(
                                color: _pickedLat == null ? Colors.grey : Colors.black87,
                                fontSize: 12,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                          child: ElevatedButton.icon(
                            onPressed: _openMap,
                            icon: Icon(Icons.map,
                                color: _pickedLat == null ? Colors.white : Colors.yellow),
                            label: Text(
                              _pickedLat == null ? 'Pick Location on Map' : 'Change Location',
                            ),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: _pickedLat == null
                                  ? const Color(0xFF67D5B5)
                                  : Colors.blueGrey,
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(vertical: 12),
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),

                    // Search Radius Slider
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            const Icon(Icons.radar, size: 18, color: Color(0xFF67D5B5)),
                            const SizedBox(width: 8),
                            Text(
                              'Search Radius: $_searchRadius km',
                              style: const TextStyle(
                                fontWeight: FontWeight.w600,
                                fontSize: 14,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        Slider(
                          value: _searchRadius.toDouble(),
                          min: 5,
                          max: 50,
                          divisions: 9,
                          label: '$_searchRadius km',
                          activeColor: const Color(0xFF67D5B5),
                          inactiveColor: Colors.grey[300],
                          onChanged: (value) => setState(() => _searchRadius = value.round()),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: const [
                            Text('5km', style: TextStyle(fontSize: 12, color: Colors.grey)),
                            Text('50km', style: TextStyle(fontSize: 12, color: Colors.grey)),
                          ],
                        ),
                        const SizedBox(height: 8),
                        Text(
                          _getRadiusDescription(_searchRadius),
                          style: TextStyle(
                            fontSize: 12,
                            color: Colors.grey[600],
                            fontStyle: FontStyle.italic,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),

                    _tf('Hospital / Location Name (optional)', _hospitalCtr),
                    const SizedBox(height: 12),
                    _tf('Contact Phone (optional)', _phoneCtr,
                        keyboardType: TextInputType.phone),
                  ],
                ),
              ),

              const SizedBox(height: 16),

              // Additional Notes Section
              _section(
                'Additional Information',
                _tf('Special notes or instructions for donors (optional)',
                    _notesCtr,
                    maxLines: 3),
              ),

              const SizedBox(height: 24),

              // Timer Information Card
              _buildTimerInfoCard(),

              const SizedBox(height: 16),

              // Donor Matching Preview
              _buildDonorMatchingPreview(),

              const SizedBox(height: 16),

              // Submit Button
              SizedBox(
                width: double.infinity,
                child: ElevatedButton.icon(
                  onPressed: _submitting ? null : _submit,
                  icon: _submitting
                      ? SizedBox(
                    width: 16,
                    height: 16,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      color: Colors.white,
                    ),
                  )
                      : const Icon(Icons.send, size: 20),
                  label: Text(
                    _submitting
                        ? 'Creating Request & Finding Donors...'
                        : 'Submit Blood Request',
                    style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                  ),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: _getUrgencyColor(_urgency),
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    elevation: 2,
                  ),
                ),
              ),

              const SizedBox(height: 8),

              // Info text about the process
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.blue[50],
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  children: [
                    Icon(Icons.info, color: Colors.blue[700], size: 16),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'After submission, compatible donors within $_searchRadius km will be matched immediately. Request expires in 1 hour.',
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.blue[800],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildRequestPreview() {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            _getUrgencyColor(_urgency).withOpacity(0.8),
            _getUrgencyColor(_urgency).withOpacity(0.6),
          ],
        ),
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: _getUrgencyColor(_urgency).withOpacity(0.3),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: Colors.white.withOpacity(0.2),
                      shape: BoxShape.circle,
                    ),
                    child: Icon(Icons.bloodtype, color: Colors.white, size: 20),
                  ),
                  const SizedBox(width: 8),
                  Text(
                    '$_bloodType • ${_units} unit(s)',
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ],
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(
                  _urgency.toUpperCase(),
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              Icon(Icons.location_on, color: Colors.white, size: 14),
              const SizedBox(width: 4),
              Expanded(
                child: Text(
                  _pickedAddress.isEmpty ? 'Location selected' : _pickedAddress,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                  ),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTimerInfoCard() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.orange[50],
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.orange),
      ),
      child: Row(
        children: [
          Icon(Icons.timer, color: Colors.orange[700], size: 24),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  '1-Hour Request Timer',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.orange[800],
                    fontSize: 14,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Your request will be active for 1 hour. Donors can accept your request during this time.',
                  style: TextStyle(
                    color: Colors.orange[700],
                    fontSize: 12,
                  ),
                ),
              ],
            ),
          ),
          Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: Colors.orange[100],
              shape: BoxShape.circle,
              border: Border.all(color: Colors.orange),
            ),
            child: Center(
              child: Text(
                '60m',
                style: TextStyle(
                  color: Colors.orange[800],
                  fontSize: 10,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDonorMatchingPreview() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.green[50],
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.green),
      ),
      child: Row(
        children: [
          Icon(Icons.people, color: Colors.green[700], size: 24),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Smart Donor Matching',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.green[800],
                    fontSize: 14,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Compatible donors within $_searchRadius km will be automatically matched based on blood type and location.',
                  style: TextStyle(
                    color: Colors.green[700],
                    fontSize: 12,
                  ),
                ),
              ],
            ),
          ),
          Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: Colors.green[100],
              shape: BoxShape.circle,
              border: Border.all(color: Colors.green),
            ),
            child: Center(
              child: Icon(Icons.bloodtype, color: Colors.green[700], size: 20),
            ),
          ),
        ],
      ),
    );
  }

  Widget _section(String title, Widget child) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: Colors.grey.shade200),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.03),
            blurRadius: 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontWeight: FontWeight.w700,
              color: Colors.blueGrey[900],
              fontSize: 16,
            ),
          ),
          const SizedBox(height: 12),
          child,
        ],
      ),
    );
  }

  Widget _tf(String label, TextEditingController ctr,
      {String? Function(String?)? validator, int maxLines = 1, TextInputType? keyboardType}) {
    return TextFormField(
      controller: ctr,
      maxLines: maxLines,
      validator: validator,
      keyboardType: keyboardType,
      decoration: InputDecoration(
        labelText: label,
        border: const OutlineInputBorder(),
        isDense: maxLines == 1,
        contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
      ),
    );
  }

  Widget _infoRow(String k, String v) {
    return Row(
      children: [
        Expanded(
          child: Text(k, style: const TextStyle(fontWeight: FontWeight.w600)),
        ),
        const SizedBox(width: 8),
        Expanded(
          child: Text(
            v,
            textAlign: TextAlign.right,
            style: TextStyle(
              color: Colors.blue[700],
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
      ],
    );
  }

  String _getRadiusDescription(int radius) {
    if (radius <= 10) {
      return 'Local search - ideal for urgent requests in nearby areas';
    } else if (radius <= 25) {
      return 'Medium range - covers most of Abbottabad city';
    } else {
      return 'Wide search - includes surrounding areas of Abbottabad';
    }
  }
}